# keywords: Hexo,HTML,Ben,CSS,安卓,android,Linux,linuxdeepin
# author: Ben Wong,wenbinben@gmail.com
description: 日常记录
avatar: /asset/avatar.JPG

# twitter: Ben_wenbin
# rss: atom.xml
weibo: 2656331642
# instagram: hwbinbenben

# Comment
duoshuo: amasawaseiji
# disqus:

# li
# if is_current('about')
#   a.current(href="/about")= __('About')
# else
#   a(href="/about")= __('About')
# li
#   if is_current('links')
#     a.current(href="/links")= __('Links')
#   else
#     a(href="/links")= __('Links')
